apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClassName }}
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolumeName }}
spec:
  capacity:
    storage: {{ .Values.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storageClassName }}
  local:
    path: {{ .Values.path | quote }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            {{- range $key, $value := .Values.nodeSelector }}
            - key: {{ $key | quote }}
              operator: In
              values:
                - {{ $value | quote }}
            {{- end }}
